print("Hello GitHub 🚀")
print("Je progresse sur Git 😎")
print("Je suis sur une branche 😎")
print("Modifié depuis GitHub 😎")
print("Nouvelle modif locale 💻")
print("Modif depuis GitHub 🌍")
print("Feature login 🔐")
print("Nouvelle feature login v2 🔐")